
// Objective-C API for talking to the following Go packages
//
//	github.com/fatedier/frp/cmd/frpc
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Frpclib_FRAMEWORK_H__
#define __Frpclib_FRAMEWORK_H__

#include "Frpclib.objc.h"
#include "Universe.objc.h"

#endif
